name: DebugBuild

on:
  push:
    branches:
      - master

env:
  SOLUTION_FILE_PATH: Project/AOENGINE.slnx
  CONFIGURATION: Debug
  PLATFORM: x64

jobs:
  build:
    # Use a Windows self-hosted runner that has Visual Studio 2026 / MSVC v145 installed.
    runs-on: [self-hosted, Windows, X64, VS2026]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v3
        with:
          msbuild-architecture: x64
          vs-version: '[18.0,19.0)'

      - name: Build
        shell: pwsh
        run: |
          msbuild $env:SOLUTION_FILE_PATH /m /p:Platform=$env:PLATFORM /p:Configuration=$env:CONFIGURATION
