name: ReleaseBuild

on:
  push:
    branches:
      - master

env:
  SOLUTION_FILE_PATH: Project/AOENGINE.slnx
  CONFIGURATION: Release
  PLATFORM: x64

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v3
        with:
          msbuild-architecture: x64
          vs-version: '[18.0,19.0)'

      - name: Show MSBuild path
        shell: pwsh
        run: |
          where.exe msbuild
          msbuild -version

      - name: Build
        shell: pwsh
        run: |
          msbuild $env:SOLUTION_FILE_PATH /m /p:Platform=$env:PLATFORM /p:Configuration=$env:CONFIGURATION
